### ISSUE TITLE
`symbolics_example` notebook fails with pytket-qiskit 0.17.0

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/pytket#104]
(env) alec@psi:~/r/pytket/examples/python$ python symbolics_example.py 
a
a_1
                                                   ┌───┐┌─────────┐┌───┐                                         »
q_0: ──■───────────────────────────────────■───────┤ X ├┤ Rz(π*b) ├┤ X ├───────■─────────────────────────────────»
     ┌─┴─┐                               ┌─┴─┐┌───┐└─┬─┘└─────────┘└─┬─┘┌───┐┌─┴─┐                               »
q_1: ┤ X ├──■─────────────────────────■──┤ X ├┤ X ├──■───────────────■──┤ X ├┤ X ├──■─────────────────────────■──»
     └───┘┌─┴─┐                     ┌─┴─┐├───┤└─┬─┘                     └─┬─┘├───┤┌─┴─┐                     ┌─┴─┐»
q_2: ─────┤ X ├──■───────────────■──┤ X ├┤ X ├──■─────────────────────────■──┤ X ├┤ X ├──■───────────────■──┤ X ├»
          └───┘┌─┴─┐┌─────────┐┌─┴─┐└───┘└─┬─┘                               └─┬─┘└───┘┌─┴─┐┌─────────┐┌─┴─┐└───┘»
q_3: ──────────┤ X ├┤ Rz(π*a) ├┤ X ├───────■───────────────────────────────────■───────┤ X ├┤ Rz(π/2) ├┤ X ├─────»
               └───┘└─────────┘└───┘                                                   └───┘└─────────┘└───┘     »
«          
«q_0: ──■──
«     ┌─┴─┐
«q_1: ┤ X ├
«     └───┘
«q_2: ─────
«          
«q_3: ─────
«          
Traceback (most recent call last):
  File "symbolics_example.py", line 66, in <module>
    print_tkcirc_via_qiskit(circ)
  File "symbolics_example.py", line 57, in print_tkcirc_via_qiskit
    qiskit_qcirc = tk_to_qiskit(tkcirc)
  File "/home/alec/r/pytket/env/lib/python3.8/site-packages/pytket/extensions/qiskit/qiskit_convert.py", line 537, in tk_to_qiskit
    append_tk_command_to_qiskit(
  File "/home/alec/r/pytket/env/lib/python3.8/site-packages/pytket/extensions/qiskit/qiskit_convert.py", line 494, in append_tk_command_to_qiskit
    qcirc.global_phase += phase * sympy.pi
  File "/home/alec/r/pytket/env/lib/python3.8/site-packages/qiskit/circuit/parameterexpression.py", line 306, in __add__
    return self._apply_operation(operator.add, other)
  File "/home/alec/r/pytket/env/lib/python3.8/site-packages/qiskit/circuit/parameterexpression.py", line 255, in _apply_operation
    elif isinstance(other, numbers.Number) and numpy.isfinite(other):
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by cqc-alec** [comment]
This works again using the latest qiskit, so should be fixed in the 0.15 release.
