### ISSUE TITLE
Can't use pytket-cirq or pytket-qiskit

### ISSUE THREAD

**Issue by DuckTigger** [CQCL/pytket#18]
System version:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
pip: 20.0.2
python: 3.7.5
```

To reproduce the problem:
```
pip install pytket pytket-cirq pytket-qiskit
python
>>>import pytket
>>>pytket.cirq.cirq_to_tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pytket' has no attribute 'cirq'
>>> pytket.qiskit.qiskit_to_tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pytket' has no attribute 'qiskit'
```
This is following the method given in the documentation: [here](https://cqcl.github.io/pytket/build/html/qiskit.html)

I'm not sure how to proceed from here.
Thanks,

**Comment by ss2165** [comment]
With current versions of pytket you will need to import the extension packages explicitly, 
try doing these imports first
```
import pytket.qiskit
import pytket.cirq
````
or even better import the methods directly
```
from pytket.cirq import cirq_to_tk
from pytket.qiskit import qiskit_to_tk
```

**Comment by DuckTigger** [comment]
Thanks, that works.
