### ISSUE TITLE
Upgrading from 0.61 to 0.71 numpy error

### ISSUE THREAD

**Issue by krehermann** [CQCL/pytket#43]
I ran pip install pytket pytket_qiskit pytket_cirq -U 

I then fixed some import paths to be consistent with 0.71

The running a simple program to print a circuit ended in a stack trace 

Traceback (most recent call last):
  File "/home/krehermann/git/oreilly-qc.github.io/samples/Pytket/ch03_02_entangled_aubits.py", line 2, in <module>
    from pytket.backends.ibm import AerStateBackend, AerBackend
ModuleNotFoundError: No module named 'pytket.backends.ibm'
(qc-3.7) (base) krehermann@krehermann-Blade:~/git/oreilly-qc.github.io$ /home/krehermann/.virtualenvs/qc-3.7/bin/python /home/krehermann/git/oreilly-qc.github.io/samples/Pytket/ch03_02_entangled_aubits.py
Traceback (most recent call last):
  File "/home/krehermann/git/oreilly-qc.github.io/samples/Pytket/ch03_02_entangled_aubits.py", line 2, in <module>
    from pytket.extensions.backends.ibm import AerStateBackend, AerBackend
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/pytket/extensions/backends/ibm/__init__.py", line 12, in <module>
    from .ibm import IBMQBackend, NoIBMQAccountError
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/pytket/extensions/backends/ibm/ibm.py", line 15, in <module>
    import qiskit  # type: ignore
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/__init__.py", line 57, in <module>
    from qiskit.providers.aer import Aer
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/__init__.py", line 64, in <module>
    from .aerprovider import AerProvider
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/aerprovider.py", line 20, in <module>
    from .backends.qasm_simulator import QasmSimulator
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/backends/__init__.py", line 20, in <module>
    from .pulse_simulator import PulseSimulator
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/backends/pulse_simulator.py", line 26, in <module>
    from ..pulse.controllers.pulse_controller import pulse_controller
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/__init__.py", line 52, in <module>
    from .system_models.duffing_model_generators import duffing_system_model
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/system_models/duffing_model_generators.py", line 21, in <module>
    from .hamiltonian_model import HamiltonianModel
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/system_models/hamiltonian_model.py", line 22, in <module>
    from .string_model_parser.string_model_parser import HamiltonianParser
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/system_models/string_model_parser/string_model_parser.py", line 23, in <module>
    from .qobj_from_string import gen_oper
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/system_models/string_model_parser/qobj_from_string.py", line 18, in <module>
    from ...qutip_extra_lite import qobj_generators
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/qutip_extra_lite/qobj_generators.py", line 19, in <module>
    from . import operators as ops
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/qutip_extra_lite/operators.py", line 56, in <module>
    from .fastsparse import fast_csr_matrix, fast_identity
  File "/home/krehermann/.virtualenvs/qc-3.7/lib/python3.7/site-packages/qiskit/providers/aer/pulse/qutip_extra_lite/fastsparse.py", line 440, in <module>
    from .cy.spmath import (zcsr_transpose, zcsr_adjoint, zcsr_mult)
  File "spmath.pyx", line 1, in init qiskit.providers.aer.pulse.qutip_extra_lite.cy.spmath
  
  Manually upgrading numpy pip install numpy -U fixed the issue (upgrading from 1.19 to 1.20)
  
  I'm not a pip expert, but it seems to me that the pip install pytket* -U ought to have resolved this dependency.

**Comment by cqc-alec** [comment]
Hi,

Thank you for the report. It seems that this is actually a bug in `qiskit` version 0.23.5 (or rather in its dependency `qiskit-aer` version 0.7.4), which has been reported here: https://github.com/Qiskit/qiskit-aer/issues/1120 .

Fortunately upgrading `numpy` fixes the issue and should not affect any other functionality (as long as you are on Python 3.7+).

Please reopen if you have further difficulties.
